/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restuarantgui;

import java.awt.*;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ipae
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    public void addTable(int id, String name, int qty, double price) {
        DefaultTableModel dt = (DefaultTableModel) jTableList.getModel(); //bring table model on dt variable
        
        DecimalFormat df = new DecimalFormat("00. 00"); //format to decimal
        
        double totPrice = price * Double.valueOf(qty); // convert qty to Double then storage them on totPrice
        
        String totalPrice = df.format(totPrice); // format string from double following code above
        
        // loop all row in table
        for (int row = 0 ; row < jTableList.getRowCount();row++) {
            //
            if (name == jTableList.getValueAt(row, 1)) {
                dt.removeRow(jTableList.convertRowIndexToModel(row));// .convertRowIndexToModel(row) ลำดับ
            } else {
            }
        }
        
        Vector v = new Vector();
        
        v.add(id);
        v.add(name);
        v.add(qty);
        v.add(totalPrice);
        // call object v and bring all args keep in.
        dt.addRow(v);
        // add v to table.
    }

    public void cal() {
        int numOfRow = jTableList.getRowCount(); // return total row
        double tot = 0.0;
        
        for (int i = 0; i < numOfRow;i++) {
            double value = Double.valueOf(jTableList.getValueAt(i, 3).toString()); // pick integer value at QTY obj column to string, then tranfrom string to double value.
            tot += value; // add value to tot variable.
        }
        DecimalFormat df = new DecimalFormat("00. 00");
        lbTotalValue.setText(df.format(tot)); //call setText for set any value "tot" to lbTotalValue's operator.
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbQ1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableList = new javax.swing.JTable();
        lbTotal = new javax.swing.JLabel();
        lbCash = new javax.swing.JLabel();
        lbBalance = new javax.swing.JLabel();
        lbBalanceValue = new javax.swing.JLabel();
        txtFieldCash = new javax.swing.JTextField();
        lbTotalValue = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        menu2 = new javax.swing.JButton();
        menu3 = new javax.swing.JButton();
        lbQ2 = new javax.swing.JLabel();
        lbQ3 = new javax.swing.JLabel();
        menu4 = new javax.swing.JButton();
        lbQ4 = new javax.swing.JLabel();
        menu5 = new javax.swing.JButton();
        lbQ5 = new javax.swing.JLabel();
        lbQ6 = new javax.swing.JLabel();
        menu6 = new javax.swing.JButton();
        menu7 = new javax.swing.JButton();
        lbQ7 = new javax.swing.JLabel();
        lbQ8 = new javax.swing.JLabel();
        menu8 = new javax.swing.JButton();
        menu9 = new javax.swing.JButton();
        lbQ9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbQ1.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        lbQ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQ1.setText("0");

        jTableList.setFont(new java.awt.Font("Tamil Sangam MN", 0, 13)); // NOI18N
        jTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "Price"
            }
        ));
        jTableList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableListMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTableList);

        lbTotal.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 0, 24)); // NOI18N
        lbTotal.setText("Total :");

        lbCash.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 0, 24)); // NOI18N
        lbCash.setText("Cash :");

        lbBalance.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 0, 24)); // NOI18N
        lbBalance.setText("Balance :");

        lbBalanceValue.setFont(new java.awt.Font("Tamil Sangam MN", 0, 24)); // NOI18N
        lbBalanceValue.setText("00");

        txtFieldCash.setFont(new java.awt.Font("Tamil Sangam MN", 0, 24)); // NOI18N
        txtFieldCash.setText("0");
        txtFieldCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCashActionPerformed(evt);
            }
        });

        lbTotalValue.setFont(new java.awt.Font("Tamil Sangam MN", 0, 24)); // NOI18N
        lbTotalValue.setText("00");

        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salad.png"))); // NOI18N
        menu1.setText("1");
        menu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pizza.png"))); // NOI18N
        menu2.setText("2");
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });

        menu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padThai.png"))); // NOI18N
        menu3.setText("3");
        menu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3ActionPerformed(evt);
            }
        });

        lbQ2.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        lbQ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQ2.setText("0");

        lbQ3.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        lbQ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQ3.setText("0");

        menu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cabonala.png"))); // NOI18N
        menu4.setText("1");
        menu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu4ActionPerformed(evt);
            }
        });

        lbQ4.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        lbQ4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQ4.setText("0");

        menu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mashroomSoup.png"))); // NOI18N
        menu5.setText("2");
        menu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu5ActionPerformed(evt);
            }
        });

        lbQ5.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        lbQ5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQ5.setText("0");

        lbQ6.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        lbQ6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQ6.setText("0");

        menu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SeafoodWithRice.png"))); // NOI18N
        menu6.setText("3");
        menu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu6ActionPerformed(evt);
            }
        });

        menu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/porkWithRice.png"))); // NOI18N
        menu7.setText("1");
        menu7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu7ActionPerformed(evt);
            }
        });

        lbQ7.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        lbQ7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQ7.setText("0");

        lbQ8.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        lbQ8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQ8.setText("0");

        menu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenCurry.png"))); // NOI18N
        menu8.setText("2");
        menu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu8ActionPerformed(evt);
            }
        });

        menu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cheeseBurgerPork.png"))); // NOI18N
        menu9.setText("3");
        menu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu9ActionPerformed(evt);
            }
        });

        lbQ9.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        lbQ9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQ9.setText("0");

        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Print");

        btnDelete.setText("Del");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menu7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menu8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menu9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbQ6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbQ7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbQ8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbQ9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbBalance)
                            .addComponent(lbCash)
                            .addComponent(lbTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbBalanceValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTotalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFieldCash, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {menu4, menu5, menu6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {menu7, menu8, menu9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbQ3)
                                        .addComponent(lbQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbQ4)
                                    .addComponent(lbQ5)
                                    .addComponent(lbQ6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQ7)
                            .addComponent(lbQ8)
                            .addComponent(lbQ9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTotal)
                            .addComponent(lbTotalValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCash)
                            .addComponent(txtFieldCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbBalance)
                            .addComponent(lbBalanceValue))
                        .addGap(28, 28, 28)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbBalanceValue, lbTotalValue});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {menu1, menu2, menu3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {menu4, menu5, menu6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {menu7, menu8, menu9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3ActionPerformed
        int i = Integer.parseInt(lbQ3.getText()); //String to Int -- Integer.parseInt("String")
        ++i;  //increase by 1
        lbQ3.setText(String.valueOf(i)); //convert int i to string
        addTable(3,"Phad thai",i,4.99);
        cal();
    }//GEN-LAST:event_menu3ActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        int i = Integer.parseInt(lbQ1.getText());
        ++i;
        lbQ1.setText(String.valueOf(i));
        addTable(1,"Salad",i,4.99);
        cal();
        
    }//GEN-LAST:event_menu1ActionPerformed

    private void txtFieldCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCashActionPerformed

    private void menu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu4ActionPerformed
        int i = Integer.parseInt(lbQ4.getText());
        ++i;
        lbQ4.setText(String.valueOf(i));
        addTable(4,"Cabonala spagety",i,6.99);
        cal();
    }//GEN-LAST:event_menu4ActionPerformed

    private void menu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu6ActionPerformed
        int i = Integer.parseInt(lbQ6.getText());
        ++i;
        lbQ6.setText(String.valueOf(i));
        addTable(6,"Seafood with rice",i,6.99);
        cal();
    }//GEN-LAST:event_menu6ActionPerformed

    private void menu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu7ActionPerformed
        int i = Integer.parseInt(lbQ7.getText());
        ++i;
        lbQ7.setText(String.valueOf(i));
        addTable(7,"Pork with rice",i,4.99);
        cal();
    }//GEN-LAST:event_menu7ActionPerformed

    private void menu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu9ActionPerformed
        int i = Integer.parseInt(lbQ9.getText());
        ++i;
        lbQ9.setText(String.valueOf(i));
        addTable(9,"Cheese burger",i,5.99);
        cal();
    }//GEN-LAST:event_menu9ActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        int i = Integer.parseInt(lbQ2.getText());
        ++i;
        lbQ2.setText(String.valueOf(i));
        addTable(2,"Pizza magarita",i,9.99);
        cal();
    }//GEN-LAST:event_menu2ActionPerformed

    private void menu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu5ActionPerformed
        int i = Integer.parseInt(lbQ5.getText());
        ++i;
        lbQ5.setText(String.valueOf(i));
        addTable(5,"Mashroom soup",i,3.99);
        cal();
    }//GEN-LAST:event_menu5ActionPerformed

    private void menu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu8ActionPerformed
        int i = Integer.parseInt(lbQ8.getText());
        ++i;
        lbQ8.setText(String.valueOf(i));
        addTable(8,"Green curry",i,4.99);
        cal();
    }//GEN-LAST:event_menu8ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel dt = (DefaultTableModel) jTableList.getModel(); 
        DecimalFormat df = new DecimalFormat("00. 00");
        
        String getId = dt.getValueAt(jTableList.getSelectedRow(),0).toString(); // storage value of row selected and at 0 column change to string
        
        String selectPrice = dt.getValueAt(jTableList.getSelectedRow(),3).toString();
        //String selectQty = dt.getValueAt(jTableList.getSelectedRow(),2).toString();
        String b4Total = lbTotalValue.getText();
        //changes type  from above
        Double tempPrice = Double.parseDouble(selectPrice);
        //Double tempQty = Double.parseDouble(selectQty);
        Double tempB4Total = Double.parseDouble(b4Total);
        
        Double tt = tempB4Total - tempPrice;
        
        lbTotalValue.setText(df.format(tt));
        
        //remove product
        int rw = jTableList.getSelectedRow();
        dt.removeRow(rw);
        
        //remove qty label
        switch (getId) {
            case "1" -> lbQ1.setText("0");
            case "2" -> lbQ2.setText("0");
            case "3" -> lbQ3.setText("0");
            case "4" -> lbQ4.setText("0");
            case "5" -> lbQ5.setText("0");
            case "6" -> lbQ6.setText("0");
            case "7" -> lbQ7.setText("0");
            case "8" -> lbQ8.setText("0");
            case "9" -> lbQ9.setText("0");
            default -> System.out.println("Over");
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double tt = Double.parseDouble(lbTotalValue.getText());
        double cash = Double.parseDouble(txtFieldCash.getText());
        double diff = cash - tt;
        
        if (diff < 0) {
            System.err.println("Insuficient value");
            lbBalanceValue.setText("Insuf.");
        } else {
            System.out.println(diff);
        }
        
        String diffToString = String.format("%.2f", diff);
        System.out.println(diffToString);
        
        lbBalanceValue.setText(diffToString);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListMouseEntered

    }//GEN-LAST:event_jTableListMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableList;
    private javax.swing.JLabel lbBalance;
    private javax.swing.JLabel lbBalanceValue;
    private javax.swing.JLabel lbCash;
    private javax.swing.JLabel lbQ1;
    private javax.swing.JLabel lbQ2;
    private javax.swing.JLabel lbQ3;
    private javax.swing.JLabel lbQ4;
    private javax.swing.JLabel lbQ5;
    private javax.swing.JLabel lbQ6;
    private javax.swing.JLabel lbQ7;
    private javax.swing.JLabel lbQ8;
    private javax.swing.JLabel lbQ9;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalValue;
    private javax.swing.JButton menu1;
    private javax.swing.JButton menu2;
    private javax.swing.JButton menu3;
    private javax.swing.JButton menu4;
    private javax.swing.JButton menu5;
    private javax.swing.JButton menu6;
    private javax.swing.JButton menu7;
    private javax.swing.JButton menu8;
    private javax.swing.JButton menu9;
    private javax.swing.JTextField txtFieldCash;
    // End of variables declaration//GEN-END:variables
}
// patch Next
// add schedule operation program
// explain in a day what else customers eat.